function value = f_U1(G,U1,U2,U3,L,beta,alpha,Y,T,V)
Delta = tensor(G);
% Delta = nmodeproduct(Delta,U1,1);
% Delta = nmodeproduct(Delta,U2,2);
% Delta = nmodeproduct(Delta,U3,3);
Delta = double(ttm(Delta,{U1,U2,U3},[1,2,3]))-L;
%Delta = Delta - L;
value = (beta/2) * (norm(Delta,'fro'))^2;
% value = value + sum(dot(Y{1}-T{1}*U1,V{1}));
t= Y{1}-diff(U1,1,1);
value = value + sum(dot(t,V{1}));
%value = value + alpha/2 * norm(Y{1}-T{1}*U1,"fro")^2;
value = value + alpha/2 * norm(t,"fro")^2;
